# Generated by Django 4.0.5 on 2022-06-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_blocked_alter_profile_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_picture/default.png', upload_to='profile_picture'),
        ),
    ]
